### ISSUE TITLE
Question: Is it possible to use SwiftlySalesforce for a Bulk Api call?

### ISSUE THREAD

**Issue by bia-nca** [mike4aday/SwiftlySalesforce#20]
Is it possible to call the Bulk Api with this framework? If yes, how? Thanks

**Comment by mike4aday** [comment]
@bia-nca - You could call Swiftly Salesforce with the Bulk API, using the `custom` method on line 206 of [Salesforce.swift](https://github.com/mike4aday/SwiftlySalesforce/blob/master/Pod/Classes/Salesforce.swift). You'd create a job and add batches as needed.

Can I ask the use case? Since the Bulk API is for uploading large amounts of data, which isn't typically present on a mobile device, is it the right API?

**Comment by bia-nca** [comment]
@mike4aday thanks. I will try it. 

I want to transfer several large generated csv-files.
