### ISSUE TITLE
JSON V5 (codable) fails on nil LastactivityDate

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#49]
"dataCorrupted(Swift.DecodingError.Context(codingPath: [SwiftlySalesforce.QueryResult<AccountManager.Account>.CodingKeys.records, Foundation.(_JSONKey in _12768CA107A31EF2DCE034FD75B541C9)(stringValue: \"Index 6\", intValue: Optional(6)), AccountManager.Account.CodingKeys.LastActivityDate], debugDescription: \"Date string does not match format expected by formatter.\", underlyingError: nil))"

We used to manage nil dates.  How do we work around this?  Thx.

**Comment by pbrondum** [comment]
LastActivityDate on Account is a String - I tried to make it a date.  Please close.

**Comment by mike4aday** [comment]
@pbrondum from the error message, it appears that the issue is that the date format is "MM/DD/YYYY" rather than the longer, date-time format used for CreatedDate, LastModifiedDate, etc. 

All dates are represented as strings in the JSON returned from Salesforce, but the default decoder is using the date formatter for the longer, date-time type to decode dates from the strings.

You can solve this by manually implementing decoding for your AccountManager class or struct, and using `DateFormatter.salesforceDateFormatter` to create a date from the shorter LastActivityDate string in JSON.

See: https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types

**Comment by auctifera-josed** [comment]
Hi @mike4aday, I'm curious if you have implemented this solution for a real world scenario, how did you handle a result (query, apex rest, etc.) that returns both datetime and date fields? If I set the `decoder.dateDecodingStrategy = .formatted(DateFormatter.salesforceDateFormatter)` works if the response only contains Date fields, but a Datetime field will generate the error `debugDescription: "Date string does not match format expected by formatter."`

**Comment by mike4aday** [comment]
Hi @auctifera-josed I believe you have to define two decoders, one for each of the formats, `DateFormatter.salesforceDateFormatter` and `DateFormatter.salesforceDateTimeFormatter` and use the appropriate decoder for the particular field while manually decoding.

**Comment by mike4aday** [comment]
@auctifera-josed my earlier response (now deleted) was wrong. See our discussion and solution in issue #64 for decoding a Salesforce record that has both Date and DateTime values.
