### ISSUE TITLE
How to cast [Record] to [Account] in query result

### ISSUE THREAD

**Issue by auctifera-josed** [mike4aday/SwiftlySalesforce#52]
I'm using custom model objects with multiple queries, so I declared it like:

```
first {
    let queries = ["SELECT Name FROM Account", "SELECT Id FROM Contact", "Select Owner.Name FROM Lead"]
    return salesforce.query(soql: queries)
}.then { (results: [QueryResult<Record>]) -> () in
   let accounts = results[0].records
   let contacts = results[1].records
   let leads = results[2].records
}.catch { error in
   
}
```

My problem is that all the objects are 'Record' and not either 'Account', 'Contact' or 'Lead', I tried a simple `let accounts = results[0].records as? [Account]` which gives me a warning "Cast from '[Record]' to unrelated type '[Account]' always fails"

**Comment by mike4aday** [comment]
@auctifera-josed the issue is with Swift generics. QueryResult is defined as: 
`QueryResult<T: Decodable>: Decodable` 

So you could substitute one of your Decodable model objects for `Record` e.g. `QueryResult<Account>` -- but I don't see how you could use 3 Decodable types simultaneously. 

Try instead to create 3 separate single-object queries, add them to an array, and use the array as the arg to `fulfill` -- see line 24 in [Globals.swift](https://github.com/mike4aday/SwiftlySalesforce/blob/master/SwiftlySalesforce/Classes/Globals.swift)
