### ISSUE TITLE
Could I use this to download a file from salesforce?

### ISSUE THREAD

**Issue by bartos00** [mike4aday/SwiftlySalesforce#53]
First let me start by saying that this wrapper is incredible! I'm a huge fan! 

I'm attempting to connect to Salesforce (custom object) and I would like to download the actual file which is stored in Attachment Body field. When my QueryResult comes back it has the path to my field instead of the base64 encoded string. When I execute my soql at workbench @ developerforce I see the full base64 string. I suppose I could just use AlamoFire and issue a request to download the file, but I love the way that all of the token support is built in for this api.

Any thoughts for the best way to accomplish this using SwiftlySalesforce? Would a .custom request be the right option in this case? Could you provide an example for me for this type of request? It seems like it requires headers to be passed into it...if so should I be grabbing those from the connectedApp instance?

Thanks for all the hard work! Big thumbs up.
Bart

**Comment by mike4aday** [comment]
Hi @bartos00 could you post the SOQL so I can verify my understanding of what you're trying to do?

Is it image data? And would the method `fetchImage(path: String) -> Promise<UIImage>` work, in line 322 of [Salesforce.swift](https://github.com/mike4aday/SwiftlySalesforce/blob/master/SwiftlySalesforce/Classes/Salesforce.swift)

**Comment by bartos00** [comment]
Hey thanks for the reply...I actually have something working now!  Here is the soql that I was executing previously: "SELECT Attachment__Body__s FROM PS_Partner_Article__kav WHERE Id = 'ka0C0000000kAdsIAE'"...and when that came back in the Workbench (DeveloperForce) it showed up as a base64 string. So just assumed that I could retrieve it back in Swift as a string and then decode the base64 string so that I could write the file. It would only return the path of the custom field though and not the actual data, it just came back as "/services/data/v41.0/sobjects/PS_Partner_Article__kav/ka0C0000000kAdsIAE/Attachment__Body__s". Maybe I was missing something obvious here? This data is typically base64 string of pdf docs, txt files, excel files and other data files.

I ended up getting it to work by calling the .custom method and passing in the path to the Attachment__Body__s route. So my snippet looks like this:

salesforce.custom(method: Resource.HTTPMethod.get, baseURL: nil, path: "/services/data/v41.0/sobjects/PS_Partner_Article__kav/\(article.Id ?? "")/Attachment__Body__s", parameters: nil, headers: nil).then { (queryResult: Data) -> () in // write file here }

This call is working exactly how I'd like for it to right now. However, I do have one question for you...is this signature ok? I wasn't sure if I needed to pass the headers...I'm not passing them and it is working. Would it be better to build the headers using the accessToken from the connectedApp? Or is this working as expected? I'm just curious if this method would work if the accessToken were expired for some reason (unlikely...but still possible)?

Thanks again for a great project. I really love how the authentication is handled and I think the code is so succinct and smooth!  HA! Keep up the good work!

**Comment by mike4aday** [comment]
@bartos00 yes, `Salesforce.custom` and converting the resulting `Data` to text is how I'd do it, too. 

The `headers` argument is for *additional* headers -- you don't need to put the access token in there since Swiftly Salesforce does that for you before sending the request. In your case, `headers` would be `nil`, just as you did it. 

Re. token expiration: the `custom` method will work just like all the other methods. If the session token has expired, then Swiftly Salesforce will try to 'silently' refresh it -- if that fails, Swiftly Salesforce will redirect the user to the Salesforce-hosted login form where the user can authenticate and authorize your app. Salesforce will issue a new access token and Swiftly Salesforce will automatically add that to the header of every request, until it expires and the process repeats.

Thanks for the kind feedback - glad to hear it's useful for you!

**Comment by mike4aday** [comment]
@bartos00 P.S. I believe the query feature in Workbench uses SOAP, which returns the actual article body. But the REST API returns a path to the article body, as you discovered, rather than the encoded body. I haven't tried this, but I believe if you use the REST explorer in Workbench and submit the SOQL to the REST `query` endpoint, you'll see that you get a path to the body in the result, not the body itself. In other words - it's a REST vs. SOAP API issue, not directly related to Swift, or Swiftly Salesforce.

**Comment by bartos00** [comment]
Ok, now that makes a lot of sense...I feel like I should have thought of that!  ;)

Appreciate your hard work and taking the time to chat with me.
