### ISSUE TITLE
 Transition to SafariWebView if the identity method is offline

### ISSUE THREAD

**Issue by daichi1021** [mike4aday/SwiftlySalesforce#60]
If an error occurs in the identity method, it becomes uniform RequestError.userAuthenticationRequired, so if you call it with the iPhone offline, it will transition to SafariWebView.

**Comment by mike4aday** [comment]
@daichi1021 is this specific to the `identity` call? Any method in the `Salesforce` class should act the same way, no? That is, if you call any method such as `query`, `update` or `insert` the user would get redirected to the Safari web view for login if there isn't a valid token.

This is intentional, though I'm open to a better way. The assumption is that you'll check for connectivity first, and not even call a `Salesforce` method if there is no Internet connection. What would you like to happen instead? Throw an "offline error" instead, and you'd catch that?

Thanks

**Comment by daichi1021** [comment]
@mike4aday 

thank you for your answer.

I feel that there is a problem unique to the salesforce.identity method.
For example, if you call the salesforce.apex method offline, an offline error will be returned, but if it is salesforce.identity it will transition to SafariWebView.

This is reproduced also when you exchange identity and apex in the same process.

**Comment by mike4aday** [comment]
@daichi1021 thanks for the follow-up. I'll check into this as soon as I can.

**Comment by mike4aday** [comment]
Thank you again, @daichi1021 - I could reproduce this and it's a bug. I'll fix it soon.

**Comment by mike4aday** [comment]
Fixed with version 6.0.5.
Thank you @daichi1021
